In [5]:
import numpy as np
import sys


In [12]:
a= np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [7]:
b= np.array([[9.0,8.0,7.0],[3.0,4.0,7.0]])
print(b)

[[9. 8. 7.]
 [3. 4. 7.]]


In [8]:
# geting dimension

a.ndim

1

In [9]:
# get shape
b.shape


(2, 3)

In [11]:
# get type
a.dtype

dtype('int32')

In [16]:
# get size

a.itemsize
b.itemsize

8

In [15]:
# get total size
a.nbytes

6

In [17]:
# ACCESISING/CHANGING SPECIFIC ELEMTS


a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
#get a specific elelmt [r,c]

a[1,5]


11

In [21]:
#specific row

a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
# specific column

a[:,2]

array([ 3, 10])

In [24]:
# [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [27]:
#to chnage an element
a[1,5]=20
print(a)

a[:,2]= [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [28]:
 #3d

b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
#geting specific
b[0,1,1]

4

In [33]:
# INITIALIZING DIFF ARRAYS

#ALL ZEROES MATRIX
np.zeros(4)
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
 # all 1s matrix
np.ones(2)

array([1., 1.])

In [35]:
# any other number
np.full((2,2),15)

array([[15, 15],
       [15, 15]])

In [38]:
# Any other number (full_like)

np.full_like(a,4)
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [42]:
# random decomal numbers

np.random.rand(4,2)

array([[0.10147579, 0.16820355],
       [0.26382753, 0.16519933],
       [0.24618046, 0.2553255 ],
       [0.82345951, 0.57998231]])

In [47]:
# random integer vales

np.random.randint(7,size=(3,3))

array([[4, 0, 0],
       [2, 5, 3],
       [4, 0, 5]])

In [48]:
# identitiy matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
# repeat an array
arr= np.array([[1,2,3]])
r1= np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [56]:
#problem 1

output= np.ones((5,5))
print(output)

z= np.zeros((3,3))
z[1,1]= 9
print(z)

output[1:4,1:4]= z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [59]:

a= np.array([1,2,3])
b= a.copy()
b[0]=100

print(b)
print(a)

[100   2   3]
[1 2 3]


In [60]:
# MATHEMATICS IN NUMPY

a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [61]:
a+2

array([3, 4, 5, 6])

In [62]:
a-2

array([-1,  0,  1,  2])

In [63]:
a*2

array([2, 4, 6, 8])

In [64]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [65]:
b= np.array([3,4,5,6])

a+b

array([ 4,  6,  8, 10])

In [67]:
#take the sin

np.sin(a)
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# LINEAR ALGEBRA


In [70]:
a= np.ones((2,3))
print(a)

b= np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [71]:
#finding determinant
c= np.identity(3)
np.linalg.det(c)

1.0

statistics

In [72]:
stats= np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
np.min(stats)

1

In [74]:
np.max(stats)

6

In [76]:
np.sum(stats, axis=0)

array([5, 7, 9])

Reorganizing Arrays

In [77]:
before= np.array([[1,2,3,8],[4,5,6,9]])
print(before)

after= before.reshape((8,1))
print(after)

[[1 2 3 8]
 [4 5 6 9]]
[[1]
 [2]
 [3]
 [8]
 [4]
 [5]
 [6]
 [9]]


In [79]:
#v vertically stacking vectors

v1= np.array([1,2,3,4])
v2= np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [81]:
# horizontal stack

h1= np.ones((2,4))
h2= np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Boolean Masking and advanced indexing


In [82]:
# we can index with a list in numpy

a= np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])